#!/usr/bin/env sh

# ██████╗ ██╗██╗   ██╗███████╗██████╗
# ██╔══██╗██║██║   ██║██╔════╝██╔══██╗
# ██████╔╝██║██║   ██║█████╗  ██████╔╝
# ██╔══██╗██║╚██╗ ██╔╝██╔══╝  ██╔══██╗
# ██║  ██║██║ ╚████╔╝ ███████╗██║  ██║
# ╚═╝  ╚═╝╚═╝  ╚═══╝  ╚══════╝╚═╝  ╚═╝

# Trace if debug.
if [ -n "$DEBUG_DOTS" ]; then
  set -x
fi

#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# AUTOSTART  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

riverctl spawn 'kanshi'
riverctl spawn 'kile -n lns'
riverctl spawn 'yambar'
riverctl spawn 'foot --server'
riverctl spawn 'pipewire'
riverctl spawn 'pipewire-pulse'
riverctl spawn 'emacs --daemon'
riverctl spawn '/usr/libexec/xdg-desktop-portal-wlr'
riverctl spawn '/usr/libexec/xdg-desktop-portal -r'


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# VARS - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

mod="Mod4"
rightOfSpace=""


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# LAYOUT - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# New views go to bottom of stack so top-view (our main) isn't moved.
riverctl attach-mode bottom

# Set the layout on startup.
riverctl output-layout 'lns'

# Kile layouts and configuration.
riverctl send-layout-cmd lns 'main_factor 0.5'
# - - Layouts per tag.
riverctl send-layout-cmd lns 'focused all ( v: h h )'
# - - Padding.
riverctl send-layout-cmd lns 'outer_padding 7'
riverctl send-layout-cmd lns 'view_padding 3'
# ---/

# `app-ids` of views which should float.
riverctl float-filter-add "float"
riverctl float-filter-add "popup"


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# INPUT  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# key repeat rates
riverctl set-repeat 72 250

# mouse
riverctl input 5426:145:Razer_Razer_Viper_8KHz natural-scroll enabled
riverctl input 5426:145:Razer_Razer_Viper_8KHz pointer-accel -1


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# APPEARANCE - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

riverctl background-color 0x635657
riverctl border-width 1
riverctl border-color-focused 0xD2BDF7
riverctl border-color-unfocused 0x6B617D
# riverctl xcursor-theme retrosmart-xcursor-black-shadow/

#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# VIEWS & MAPS - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# launcher
riverctl map normal "$mod" R spawn fuzzel

# close the focused view
riverctl map normal "$mod" Q close

# terminal emulator
riverctl map normal "$mod"+Shift Return spawn foot
# riverctl map normal "$mod"+Mod1 R spawn foot

# exit river
riverctl map normal "$mod"+"Mod1" E exit

# zoom current view
riverctl map normal "$mod" Return zoom

# mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal "$mod" J focus-view next
riverctl map normal "$mod" K focus-view previous

# mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal "$mod"+Shift J swap next
riverctl map normal "$mod"+Shift K swap previous

# mod+Left-Mouse-Button to move views
riverctl map-pointer normal "$mod" BTN_LEFT move-view

# lock screen
riverctl map normal "$mod"+Shift X spawn waylock


#  - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# TAGS - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
for i in $(seq 1 6); do
    tagmask=$((1 << ($i - 1)))

    # mod+[1-N] to focus tag [0-(N-1)]
    riverctl map normal "$mod" "$i" set-focused-tags "$tagmask"

    # mod+Shift+[1-N] to tag focused view with tag [0-(N-1)]
    riverctl map normal "$mod"+Shift "$i" set-view-tags "$tagmask"

    # mod+Ctrl+[1-N] to toggle focus of tag [0-(N-1)]
    # riverctl map normal $mod+Control $i toggle-focused-tags $tagmask

    # mod+Shift+Ctrl+[1-N] to toggle tag [0-(N-1)] of focused view
    # riverctl map normal $mod+Shift+Control $i toggle-view-tags $tagmask
done

# mod+0 to focus all tags
# mod+Shift+0 to tag focused view with all tags
all_tags_mask=$(((1 << 32) - 1))
riverctl map normal "$mod" 0 set-focused-tags "$all_tags_mask"
riverctl map normal "$mod"+Shift 0 set-view-tags "$all_tags_mask"





# # Mod+J and Mod+K to focus the next/previous view in the layout stack
# riverctl map normal "$mod" J focus-view next
# riverctl map normal "$mod" K focus-view previous

# # Mod+Period and Mod+Comma to focus the next/previous output
# riverctl map normal "$mod" Period focus-output next
# riverctl map normal "$mod" Comma focus-output previous

# # Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
# riverctl map normal "$mod"+Shift Period send-to-output next
# riverctl map normal "$mod"+Shift Comma send-to-output previous

# # Mod+Return to bump the focused view to the top of the layout stack, making
# # it the new master
riverctl map normal "$mod" Return zoom

# # decrease/increase the width of the master column by 5%
# riverctl map normal "$mod" H mod-master-factor -0.05
# riverctl map normal "$mod" L mod-master-factor +0.05

# # Mod + Left Mouse Button to move views
# riverctl map-pointer normal $mod BTN_LEFT move-view

# # Mod + Right Mouse Button to resize views
# riverctl map-pointer normal $mod BTN_RIGHT resize-view

# for i in $(seq 1 9); do
#     tagmask=$((1 << ($i - 1)))

#     # Mod+[1-9] to focus tag [0-8]
#     riverctl map normal "$mod" "$i" set-focused-tags "$tagmask"

#     # Mod+Shift+[1-9] to tag focused view with tag [0-8]
#     riverctl map normal "$mod"+Shift "$i" set-view-tags "$tagmask"

#     # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
#     riverctl map normal "$mod"+Control "$i" toggle-focused-tags "$tagmask"

#     # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
#     riverctl map normal "$mod"+Shift+Control "$i" toggle-view-tags "$tagmask"

# done

# # Mod+0 to focus all tags
# # Mod+Shift+0 to tag focused view with all tags
# all_tags_mask=$(((1 << 32) - 1))
# riverctl map normal $mod 0 set-focused-tags $all_tags_mask
# riverctl map normal $mod+Shift 0 set-view-tags $all_tags_mask

# # Mod+Space to toggle float
riverctl map normal $mod Space toggle-float

# # Mod+F to toggle fullscreen
# riverctl map normal $mod F toggle-fullscreen

# # Mod+S to change to Full layout
# riverctl map normal $mod S layout full
