inherits = "sonokai"

# TODO: This theme.

"ui.cursor.primary.normal" = { fg = "black", bg = "electric_yellow" }
"ui.cursor.primary.select" = { fg = ""#00FFFF" }
"ui.cursor.primary.insert" = { fg = "black", bg = ""#FF0000", modifiers = ["slow_blink"] }

"ui.statusline.normal" = { fg = "black", bg = "electric_yellow" }
"ui.statusline.insert" = { fg = ""#FFFFFF", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "black", bg = "electric_cyan" }

"ui.cursor.match" = { fg = ""#FFFF00", bg = "diff_yellow", modifiers = ["underlined"] }

# "ui.statusline" = ""#FF0000"
# "ui.window" = ""#FF0000"

[palette]
# My colours.
electric_yellow = ""#FFFF00"
electric_cyan = ""#00FFFF"

# Alternate Sonokai pallete from official theme.
black = "#181a1c"
bg0 = "#2b2d3a"
# bg0 = ""#1e1e2e" # Cap base.
# bg0 = ""#181825" # Cap mantle.
# bg0 = ""#11111b" # Cap crust.
bg1 = "#333648"
bg2 = "#363a4e"
bg3 = "#393e53"
bg4 = "#3f445b"
bg_red = "#ff6188"
diff_red = "#55393d"
bg_green = "#a9dc76"
diff_green = "#394634"
bg_blue = "#77d5f0"
diff_blue = "#354157"
diff_yellow = "#4e432f"
fg = "#e1e3e4"
red = "#fb617e"
orange = "#f89860"
yellow = "#edc763"
green = "#9ed06c"
cyan = "#ef9062" # added for compatibility with `edge` scheme
blue = "#6dcae8"
purple = "#bb97ee"
grey = "#7e8294"
grey_dim = "#5a5e7a"

