#!/bin/bash

# numlock on by default, and multi-language input
numlockx &
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx

# openbox
exec openbox & PID="$!"
sleep 0.05

# TODO: abstract generating this to the bash setup command
if [ $(pidof openbox) ]; then
  # display layout
  xrandr --output DisplayPort-1 --primary --mode 2560x1440 --pos 1080x560 --rotate normal \
         --output DisplayPort-2 --mode 2560x1440 --pos 3640x0 --rotate right \
         --output HDMI-A-0 --mode 2560x1080 --pos 0x79 --rotate left

  # set modifier key mappings we desire
  # xmodmap "$XDG_CONFIG_HOME"/x/xmodmap

  # set cursor theme and size
  xrdb "$XDG_CONFIG_HOME"/x/xresources

  # set key delay and repeat speeds
  xset r rate 200 50
  # keeps unsetting itself, setting via startx instead via...
  # startx -- -ardelay 200 -arinterval 50

  picom &
  "$XDG_CONFIG_HOME"/feh/setbg.sh &
  "$XDG_CONFIG_HOME"/polybar/launch.sh &

  # here instead of "$XDG_CONFIG_HOME"/openbox/autostart for portability
  # start at login
  discord &
  slack &
  kitty --title music ncspot &
  kitty --title irc weechat &

  # position those started at login
  # left screen
  wmctrl -r "Discord" -e "0,5,84,1068,680" &
  wmctrl -r "irc" -e "0,6,818,1068,630" &
  wmctrl -r "Slack" -e "0,5,1458,1068,770" &
  wmctrl -r "music" -e "0,6,2282,1068,347" &
fi

wait "$PID"
