# theme = "tsukai"
# theme = "ayu_evolve"
theme = "tsuvendi"
# theme = "catppuccin_mocha"
# theme = "ayu_dark"
# rose_pine_moon
# wombat
# hurtado

[editor]
line-number = "relative"
# TODO: Pr for thinner rulers? A line or stippled line? Copy the character from the indent guide line?
rulers = [80, 120]
shell = ["/usr/bin/env", "bash", "-c"]
bufferline = "always"
cursorline = true
color-modes = true
# Force true color and undercurl on.
true-color = true
undercurl = true

[editor.whitespace.render]
space = "all"
tab = "all"
nbsp = "none"
nnbsp = "none"
newline = "all"

[editor.soft-wrap]
enable = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "hidden"

[editor.file-picker]
hidden = false

[editor.indent-guides]
# TODO: Pr to highlight indent level?
# character = "▏"
character = "┊"
render = true
skip-levels = 1

[editor.statusline]
# Default right = ["diagnostics", "selections", "position", "file-encoding"] 
# Default left = ["mode", "spinner", "file-name"]
# Default separator = "│"
# "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

separator = "/"

left = [
  "mode",
  "spacer",
  "spinner",
  # TODO: PR to add abbreviated path e.g. instead of `helix/config.toml` it
  #       would be `h/config.toml`, so a deeply nested file would appear as
  #       `a/b/c/De/f/g/config.toml` for instance.
  "file-name",
  "file-modification-indicator",
]

center = [
  "primary-selection-length",
  "selections",
]

right = [
  "spacer",
  "spacer",
  "diagnostics",
  "version-control",
  # "spacer",
  # "separator",
  # "separator",
  "spacer",
  # "separator",
  "file-type",
  "file-encoding",
  "file-line-ending",
  # "spacer",
  "position",
  "separator",
  "total-line-numbers",
]

[keys.normal.space]
"H" = ":toggle lsp.display-inlay-hints"

[keys.normal]
C-p = ["move_line_up", "scroll_up"]
C-n = ["move_line_down", "scroll_down"]

x = ["extend_line"] # Default is `extend_line_below`

# Transpose lines (no need to select too).
C-j = ["extend_to_line_bounds", "delete_selection", "paste_after"]
C-k = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]

# Normally ; to deselect a selection and , to go back to a single cursor from
#   multiple. Now esc can do those too.
# TODO: This also dismisses the shell command buffer capture though which is annoying, test esc ; , with that popup
#       with this line commented to see what happens by default. PR a fix if required.
esc = ["collapse_selection", "keep_primary_selection"]
